### ISSUE TITLE
Firmware source-code & binary for Nebula rev 2.0 IOT DEVELOPMENT KIT

### ISSUE THREAD

**Issue by aniruddhanalgirkar-eaton** [winkj/wiced-ess#2]
- I am looking for the Firmware source-code & binary for Nebula rev 2.0 IOT DEVELOPMENT KIT. (I can see the default f/w has some application running & it scans if seen on TeraTerm / console). Can anyone point to the right f/w & it's binary?

- Also, this board has USB DEBUG port. I believe it's not same as ST-Link, J-Link, etc. What flash tool is it using?

**Comment by winkj** [comment]
Hi there,

this github project is for a particular sensor board that can be used with Nebula, not the Nebula development kit itself, as such, we won't be able to help with your requests. I would recommend reaching out to the manufacturer of the product instead!
